### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by YesThatGy** [tomassasovsky/tus_client#14]
When I try to compile the example, I get compiling errors, see compile.errors.txt 
See environment.txt for details about my environment. Here's what I do to reproduce the errors - they are persistent and show almost immediately. 

[environment.txt](https://github.com/user-attachments/files/16517876/environment.txt)
[compile.errors.txt](https://github.com/user-attachments/files/16517879/compile.errors.txt)

gh repo clone tomassasovsky/tus_client
cd tus_client/example
flutter pub get 
flutter pub outdated
flutter pub outdated --major-versions
flutter pub get 
# see errors in compile

**Comment by YesThatGy** [comment]
bens@tesla:~/development/tus_client$ java --version
openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (Red_Hat-21.0.4.0.7-2) (build 21.0.4+7)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.4.0.7-2) (build 21.0.4+7, mixed mode, sharing)

**Comment by tomassasovsky** [comment]
Thanks for your report! Please `git pull` and try again. Should work now.

**Comment by YesThatGy** [comment]
It works! Thank you very much

**Comment by tomassasovsky** [comment]
Awesome! Thank you for using `tus_client_dart`!

**Comment by YesThatGy** [comment]
Do you want feedback or code improvements on example? 

I've been playing around with the example and I've noticed it can create corrupted uploads because the handler for the Upload button is async so it's creating multiple threads if you tap the button multiple times. 

If you know this, you can upload multiple files at once by: 
1) Click Upload a file 
2) click Upload
3) Don't wait! Just click Upload a file again
4) click Upload 
5) Repeat as many times as you want. I suppose if you do it enough times, the app will crash. 

The UI is based on singletons but singletons aren't enfoced. Want to see where I take it?
