### ISSUE TITLE
 Inquiry About Package Updates and Stability

### ISSUE THREAD

**Issue by jbarasa** [tomassasovsky/tus_client#16]
Hello,

First, I want to thank you for your work on the [tus_client_dart ](https://pub.dev/packages/tus_client_dart), I'm new to using the [tus_client_dart ](https://pub.dev/packages/tus_client_dart) package and noticed that the last commit was two months ago, while the version on pub.dev is 16 months old. I wanted to ask if there are any plans for future updates or if the package is considered stable for ongoing use.

Thank you for your time!

**Comment by tomasatisocco** [comment]
> Hello,
> 
> First, I want to thank you for your work on the [tus_client_dart ](https://pub.dev/packages/tus_client_dart), I'm new to using the [tus_client_dart ](https://pub.dev/packages/tus_client_dart) package and noticed that the last commit was two months ago, while the version on pub.dev is 16 months old. I wanted to ask if there are any plans for future updates or if the package is considered stable for ongoing use.
> 
> Thank you for your time!

We are actually using the package in the version 2.5.0 so it should work correctly
